### ISSUE TITLE
Claiming

### ISSUE THREAD

**Issue by Voidserror** [MasterSloth1/Sloth-s-Hack-n-Slash-Adventure#3]
So uh, since I haven't found any way to claim, I'm assuming it does not exist, hence I'm requesting any sort of claim system.

In the start I sorta found a base really close to spawn that wasn't raided, but looked like it had been abandoned a pretty long time, I didn't want to take anything due to the rules, and in case that person might come back only to find nothing(can relate). 

But.. Others might not be as considerate. And I don't want my own base to get raided too, so could you please try to find some sort of claim system?

Have a nice day! ^^
~Void, Voidserror.

**Comment by MasterSloth1** [comment]
use nomadic tents to claim your stuff when you log off the server just disassemble the tent and hold it in your inventory

**Comment by MasterSloth1** [comment]
at some point i will add a land claim system
