### ISSUE TITLE
Mana infusion broke.

### ISSUE THREAD

**Issue by Voidserror** [MasterSloth1/Sloth-s-Hack-n-Slash-Adventure#5]
**What version of the pack are you running?** 4.2

**do you have optifine installed?** Nope

**ram allocated** 7424MB

**Describe the bug**
I don't know if this is a bug or not, but the mana infusion thingie seems to have random stuff just shoved in there. One recipie I saw you could turn opal shards into silver blocks, erm..

**To Reproduce**
1.  You go into any item that has mana infusion involved
2. Click on the mana infusion, and look at the recipies
3. Scroll around the tabs and look at all the randomness, some things look more custom, others just look random

**Screenshots**
![image](https://user-images.githubusercontent.com/59747214/77556856-4db60100-6eb9-11ea-8ed8-cd3d71d86e22.png)
![image](https://user-images.githubusercontent.com/59747214/77556889-5ad2f000-6eb9-11ea-984d-45fcf86a1dac.png)
![image](https://user-images.githubusercontent.com/59747214/77556932-66261b80-6eb9-11ea-9aca-3d5d9b0504fe.png)
![image](https://user-images.githubusercontent.com/59747214/77556959-6f16ed00-6eb9-11ea-948e-1318e988ae04.png)
![image](https://user-images.githubusercontent.com/59747214/77556969-73430a80-6eb9-11ea-9ec5-6a60512826bb.png)

**Additional context**
I found this out by looking up recipies for night vision goggles, turns out you can turn vertical elder prismarine slabs into techy goggles with mana.

**Comment by BedrockLegends** [comment]
This is not a bug or issue, this however is a Mod adding/supporting other types of stuff in it
