### ISSUE TITLE
My friend BuddyEatsMelon1 is struggling to get into the pack, crashing upon launching, unexpected error.

### ISSUE THREAD

**Issue by Voidserror** [MasterSloth1/Sloth-s-Hack-n-Slash-Adventure#6]
**What version of the pack are you running?** 4.2

**do you have optifine installed?** No optifine.

**ram allocated** 6-8gb

**Describe the bug** Pack crashes saying unexpected error occured as soon as I launch from the native launcher.

**To Reproduce**
1.  Launch the pack from the native launcher
2.  Instantly crashes
3. "Unexptected error has occured"

**Screenshots**
Screenshot given was a bit irrelevant.

**Additional context**
These were answers submitted by Buddy, but he hasn't gotten into the server yet, cause well, crashing, dunno about the discord though. If this bug gets fixed you'll have a new player, depending on if he likes mine and slash or not, he might become about as active as me.

**Comment by BedrockLegends** [comment]
Closed as 4.2 is alpha and is not meant for players to use or play with, till sloth said other wise.

Also just tested 4.2 and got no crash on launch from Twitch

**Comment by BedrockLegends** [comment]
Just confirmed that when I launch 4.2, it does not crash on Launch of pack from Twitch
